test: &default

  # Credentials for REST APIs
  #client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_id: AcIxZcXA9fR69T4K8XRoZJiCo8j5IEGc_jG1pERPodILoGnyMxs3kHVGeVN4bZ7tM2NpMVcGFaNGlUWp
  #client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM
  client_secret: ECcUUEIqZBZoW0Zb8GlHZiyJ4_mbuXAMQWW8Phk7Hj5KsYpYX1dsTAwgqyMRCaJq_Fz_BkxHcURwjDmn
  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: verybluetomatos-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
