# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 507608715aee6c1c06b6a073e4020198e81cd1b7355df19d62af3adfb45024dc8de8dd73a2c19a2b6cba30bb167056fd132f0a250a2fb49ac8b2bd43f0756392

test:
  secret_key_base: 336efb0a78b286d37f9d3f4028e79f25a556eadb415124a79d4221d9e705dc9b346f4fc466b1a5b13b9b24c97eb3a7f6c406a1d93b8ec8324e12494efe2b2177

development:
  paypal_host: https://www.sandbox.paypal.com
  secret_key_base: ECcUUEIqZBZoW0Zb8GlHZiyJ4_mbuXAMQWW8Phk7Hj5KsYpYX1dsTAwgqyMRCaJq_Fz_BkxHcURwjDmn
  app_host: http://localhost:3000

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  paypal_host: https://www.sandbox.paypal.com
  app_host: https://warm-cove-74583.herokuapp.com
  secret_key_base: ECcUUEIqZBZoW0Zb8GlHZiyJ4_mbuXAMQWW8Phk7Hj5KsYpYX1dsTAwgqyMRCaJq_Fz_BkxHcURwjDmn
